#!/usr/bin/env python3

from sys import argv
from os import getcwd
from os.path import isfile

ARG_LEN = 2
FILE_INDEX = 1

EXIT_SUCCESS = 0
EXIT_FAILURE = 1 

def main():
    if len(argv) != ARG_LEN:
        print("Usage: bm [filename]")
        return EXIT_FAILURE

    comp = None           # Compiler to use.
    src = None            # Program source file.
    ext = None            # extension for source file.
    target = None         # Name of output file.

    src = argv[FILE_INDEX]
    if not isfile(src):
        print("Invalid source file (does it exist?): " + src)
        return EXIT_FAILURE

    ext = src[src.find('.'):]
    if ext == ".c":
        comp = "gcc"
    elif ext == ".cpp":
        comp = "g++"
    else:
        print("Invalid extension: " + ext + ". Options are: .c, .cpp")
        return EXIT_FAILURE

    target = src[:src.find('.')]
    
    path = getcwd() + "/makefile"
    # Prevent accidental deletions. 
    if isfile(path):
        print("Warning! Makefile found at: " + path + ". Remove this from path before continuing!")
        return EXIT_FAILURE
    
    with open(path, "w") as makefile:
        message = f'CC = {comp}\n'
        message += f'EXT = {ext}\n'
        message += 'CFLAGS = -g -Wall\n\n'
        message += f'TARGET = {target}\n\n'
        message += '$(TARGET):$(TARGET)$(EXT)\n'
        message += '\t$(CC) $(CFLAGS) -o $(TARGET) $(TARGET)$(EXT)\n\n'
        message += 'clean:\n'
        message += '\t$(RM) $(TARGET)\n'
        
        makefile.write(message)
    
    return EXIT_SUCCESS

if __name__ == "__main__":
    main()
